# Generated by Django 4.1.7 on 2023-03-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='files',
            field=models.FileField(default=None, null=True, upload_to='jobs/file/'),
        ),
    ]
