# Generated by Django 4.1.7 on 2023-03-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0034_alter_jobpost_pub_date'),
        ('jobs', '0002_alter_docs_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hire.jobpost', verbose_name='Foreign Key'),
        ),
    ]
