# Generated by Django 4.1.7 on 2023-03-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_docs_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='files',
        ),
        migrations.AddField(
            model_name='docs',
            name='files_cl',
            field=models.FileField(default=None, null=True, upload_to='jobs/CoverLetters/'),
        ),
        migrations.AddField(
            model_name='docs',
            name='files_resume',
            field=models.FileField(default=None, null=True, upload_to='jobs/resume/'),
        ),
    ]
