# Generated by Django 4.1.7 on 2023-03-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_docs_first_name_docs_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
