# Generated by Django 4.1.7 on 2023-03-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_desc',
            field=models.CharField(default='00', max_length=50),
        ),
    ]
