# Generated by Django 4.1.7 on 2023-03-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_rename_job_desc_jobpost_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='id',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='experience',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
