# Generated by Django 4.1.7 on 2023-03-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_remove_jobpost_id_jobpost_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
