# Generated by Django 4.1.7 on 2023-03-03 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0035_alter_jobpost_pub_date_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 3, 3, 22, 48, 25, 740319)),
        ),
    ]
