# Generated by Django 4.1.7 on 2023-03-03 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0037_alter_jobpost_pub_date_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 3, 3, 23, 36, 52, 556203)),
        ),
    ]
