# Generated by Django 4.1.7 on 2023-03-04 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0038_alter_jobpost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted',
            name='coverLetter',
            field=models.FileField(default=None, max_length=50, upload_to='jobs/delete/covers'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 3, 4, 11, 10, 28, 259816)),
        ),
    ]
