# Generated by Django 4.1.7 on 2023-03-04 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0039_alter_deleted_coverletter_alter_jobpost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='sno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='sno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 3, 4, 11, 18, 1, 545874)),
        ),
    ]
