# Generated by Django 4.1.7 on 2023-03-04 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0040_alter_accepted_sno_alter_deleted_sno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 3, 4, 11, 18, 31, 993773)),
        ),
    ]
