# Generated by Django 4.1.7 on 2023-03-04 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0041_alter_jobpost_job_id_alter_jobpost_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='branch',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 3, 4, 22, 33, 6, 681740)),
        ),
    ]
